name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.TF_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: HashiCorp - Setup Terraform

        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Run terraform init
        run: terraform init

      - name: Run terraform format
        run: terraform fmt -check

      - name: Run terraform plan
        run: terraform plan

      - name: Run terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
